# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
create_project -in_memory -part xc7a200tfbg676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/loongson.cache/wt [current_project]
set_property parent.project_path /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/loongson.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/loongson.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/func/obj/inst_ram.coe
add_files /home/ysyx/zzq/Code/AssemblerLangugae/test_jmp/inst_ram.coe
add_files /home/ysyx/weihui/la32_7pipline-cpu-master28/zzq_test/test_jmp/inst_ram.coe
add_files /home/ysyx/LoogArch/loongarch_test/loongarch_test/func_point72/func/obj/inst_ram.coe
add_files /home/ysyx/LoogArch/loongarch_test/zzq_test/test_random/inst_ram.coe
add_files /home/ysyx/LoogArch/loongarch_test/zzq_test/test_idle/inst_ram.coe
add_files /home/ysyx/LoogArch/loongarch_test/zzq_test/test_cacop/inst_ram.coe
add_files -quiet /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/rtl/xilinx_ip/axi_ram/axi_ram.dcp
set_property used_in_implementation false [get_files /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/rtl/xilinx_ip/axi_ram/axi_ram.dcp]
read_verilog {
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/DefineAluOp.h
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/DefineError.h
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/DefineConfg.h
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/DefineModuleBus.h
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/DefineLoogLenWidth.h
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/DefineCsrAddr.h
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/DefineSignLocation.h
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/DefineExcepSign.h
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/DefineBJSign.h
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/DefineWbSign.h
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/DefineExSign.h
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/DefineInstSign.h
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/DefineMemSign.h
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/DefineIdSign.h
}
set_property file_type "Verilog Header" [get_files /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/DefineAluOp.h]
set_property file_type "Verilog Header" [get_files /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/DefineError.h]
set_property file_type "Verilog Header" [get_files /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/DefineConfg.h]
set_property file_type "Verilog Header" [get_files /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/DefineModuleBus.h]
set_property file_type "Verilog Header" [get_files /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/DefineLoogLenWidth.h]
set_property file_type "Verilog Header" [get_files /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/DefineCsrAddr.h]
set_property file_type "Verilog Header" [get_files /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/DefineSignLocation.h]
set_property file_type "Verilog Header" [get_files /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/DefineExcepSign.h]
set_property file_type "Verilog Header" [get_files /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/DefineBJSign.h]
set_property file_type "Verilog Header" [get_files /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/DefineWbSign.h]
set_property file_type "Verilog Header" [get_files /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/DefineExSign.h]
set_property file_type "Verilog Header" [get_files /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/DefineInstSign.h]
set_property file_type "Verilog Header" [get_files /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/DefineMemSign.h]
set_property file_type "Verilog Header" [get_files /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/DefineIdSign.h]
read_mem /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/rtl/xilinx_ip/axi_ram/axi_ram.mif
read_verilog -library xil_defaultlib {
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/Arith_Logic_Unit.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/Branch_Unit.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/CountReg.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/Csr.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/Data_Relevant.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/Div.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/EX.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/EX_MEM.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/Error.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/ExStage.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/ID.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/ID_EX.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/IF.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/IF_ID.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/IdCb.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/IdSq.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/IdStage.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/IfStage.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/IfTCb.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/IfTSq.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/IfTStage.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/IndetifyInstType.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/Lanuch.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/Loog.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/MEM.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/MEM_WB.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/MMCb.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/MMSq.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/MMStage.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/MemStage.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/Mmu.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/OpDecoder.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/PreIF.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/Predict/Predactor.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/Predict/Predactor_Btb.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/Predict/Predactor_PUC.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/Predict/Predactor_Pht.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/PreifReg.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/Preif_IF.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/zzq_design_ip/Queue.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/Reg_File.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/Reg_File_Box.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/SignProduce.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/TlbGroup.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/WB.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/WbStage.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/rtl/axi_wrap/axi_wrap.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/rtl/ram_wrap/axi_wrap_ram.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/Cache/new/define.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/Cache/new/cache.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/Cache/new/cache_table.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/Cache/new/cache_way.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/rtl/CONFREG/confreg.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/zzq_design_ip/Diff/diff.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/mycpu_cache_top.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/mycpu_top.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/sramaixbridge.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/tlb.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/tools.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/paper_code3.0/wallace_mul.v
  /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/rtl/soc_lite_top.v
}
read_ip -quiet /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/Cache/ip/tagv_ram/tagv_ram.xci
set_property used_in_implementation false [get_files -all /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/Cache/ip/tagv_ram/tagv_ram_ooc.xdc]

read_ip -quiet /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/rtl/xilinx_ip/clk_pll/clk_pll.xci
set_property used_in_implementation false [get_files -all /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/rtl/xilinx_ip/clk_pll/clk_pll_board.xdc]
set_property used_in_implementation false [get_files -all /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/rtl/xilinx_ip/clk_pll/clk_pll.xdc]
set_property used_in_implementation false [get_files -all /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/rtl/xilinx_ip/clk_pll/clk_pll_ooc.xdc]

read_ip -quiet /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2.xci
set_property used_in_implementation false [get_files -all /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2_ooc.xdc]

read_ip -quiet /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/Cache/ip/data_bank/data_bank.xci
set_property used_in_implementation false [get_files -all /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/Cache/ip/data_bank/data_bank_ooc.xdc]

read_ip -quiet /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/loongson.srcs/sources_1/ip/btb_ram/btb_ram.xci
set_property used_in_implementation false [get_files -all /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/loongson.srcs/sources_1/ip/btb_ram/btb_ram_ooc.xdc]

read_ip -quiet /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/loongson.srcs/sources_1/ip/pht_ram/pht_ram.xci
set_property used_in_implementation false [get_files -all /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/loongson.srcs/sources_1/ip/pht_ram/pht_ram_ooc.xdc]

read_ip -quiet /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/loongson.srcs/sources_1/ip/axi_clock_converter/axi_clock_converter.xci
set_property used_in_synthesis false [get_files -all /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/loongson.srcs/sources_1/ip/axi_clock_converter/axi_clock_converter_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/loongson.srcs/sources_1/ip/axi_clock_converter/axi_clock_converter_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/project/loongson.srcs/sources_1/ip/axi_clock_converter/axi_clock_converter_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/constraints/soc_lite_top.xdc
set_property used_in_implementation false [get_files /home/ysyx/weihui/la32_7pipline-cpu-master28/mycpu_env/soc_verify/soc_axi/run_vivado/constraints/soc_lite_top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top soc_axi_lite_top -part xc7a200tfbg676-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_axi_lite_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_axi_lite_top_utilization_synth.rpt -pb soc_axi_lite_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
