# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/ysyx/weihui/la32_7pipline-cpu-master/mycpu_env/soc_verify/soc_axi/run_vivado/constraints/soc_lite_top.xdc

# IP: /home/ysyx/weihui/la32_7pipline-cpu-master/mycpu_env/soc_verify/soc_axi/run_vivado/project/Cache/ip/tagv_ram/tagv_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tagv_ram || ORIG_REF_NAME==tagv_ram} -quiet] -quiet
