# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ysyx/zzq/cdp_ede_local-Lab08_exp23/mycpu_env/soc_verify/soc_axi/run_vivado/project/loongson.srcs/sources_1/ip/axi_clock_converter/axi_clock_converter.xci
# IP: The module: 'axi_clock_converter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ysyx/zzq/cdp_ede_local-Lab08_exp23/mycpu_env/soc_verify/soc_axi/run_vivado/project/loongson.srcs/sources_1/ip/axi_clock_converter/axi_clock_converter_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_clock_converter'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/ysyx/zzq/cdp_ede_local-Lab08_exp23/mycpu_env/soc_verify/soc_axi/run_vivado/project/loongson.srcs/sources_1/ip/axi_clock_converter/axi_clock_converter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_clock_converter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/ysyx/zzq/cdp_ede_local-Lab08_exp23/mycpu_env/soc_verify/soc_axi/run_vivado/project/loongson.srcs/sources_1/ip/axi_clock_converter/axi_clock_converter.xci
# IP: The module: 'axi_clock_converter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ysyx/zzq/cdp_ede_local-Lab08_exp23/mycpu_env/soc_verify/soc_axi/run_vivado/project/loongson.srcs/sources_1/ip/axi_clock_converter/axi_clock_converter_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_clock_converter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/ysyx/zzq/cdp_ede_local-Lab08_exp23/mycpu_env/soc_verify/soc_axi/run_vivado/project/loongson.srcs/sources_1/ip/axi_clock_converter/axi_clock_converter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_clock_converter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
