# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/ysyx/zzq/cdp_ede_local-Lab08_exp23/mycpu_env/soc_verify/soc_axi/run_vivado/constraints/soc_lite_top.xdc

# IP: /home/ysyx/zzq/cdp_ede_local-Lab08_exp23/mycpu_env/soc_verify/soc_axi/rtl/xilinx_ip/clk_pll/clk_pll.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_pll || ORIG_REF_NAME==clk_pll} -quiet] -quiet

# IP: /home/ysyx/zzq/cdp_ede_local-Lab08_exp23/mycpu_env/soc_verify/soc_axi/rtl/xilinx_ip/axi_ram/axi_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_ram || ORIG_REF_NAME==axi_ram} -quiet] -quiet

# IP: /home/ysyx/zzq/cdp_ede_local-Lab08_exp23/mycpu_env/soc_verify/soc_axi/rtl/myCPU/IP/axi_clock_converter/axi_clock_converter.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_clock_converter || ORIG_REF_NAME==axi_clock_converter} -quiet] -quiet

# IP: /home/ysyx/zzq/cdp_ede_local-Lab08_exp23/mycpu_env/soc_verify/soc_axi/rtl/myCPU/IP/data_bank/data_bank.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_bank || ORIG_REF_NAME==data_bank} -quiet] -quiet

# IP: /home/ysyx/zzq/cdp_ede_local-Lab08_exp23/mycpu_env/soc_verify/soc_axi/rtl/myCPU/IP/tagv_ram/tagv_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tagv_ram || ORIG_REF_NAME==tagv_ram} -quiet] -quiet
