# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ysyx/zzq/Code/LoogArch/cdp_ede_local-Lab08_exp18/mycpu_env/soc_verify/soc_axi/run_vivado/project/myCPU/IP/data_bank_sram/data_bank_sram.xci
# IP: The module: 'data_bank_sram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ysyx/zzq/Code/LoogArch/cdp_ede_local-Lab08_exp18/mycpu_env/soc_verify/soc_axi/run_vivado/project/myCPU/IP/data_bank_sram/data_bank_sram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_bank_sram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/ysyx/zzq/Code/LoogArch/cdp_ede_local-Lab08_exp18/mycpu_env/soc_verify/soc_axi/run_vivado/project/myCPU/IP/data_bank_sram/data_bank_sram.xci
# IP: The module: 'data_bank_sram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ysyx/zzq/Code/LoogArch/cdp_ede_local-Lab08_exp18/mycpu_env/soc_verify/soc_axi/run_vivado/project/myCPU/IP/data_bank_sram/data_bank_sram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_bank_sram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
